### ISSUE TITLE
 `metal vlan` returns facilities not metros

### ISSUE THREAD

**Issue by displague** [StackPointCloud/packet-cli#278]
> Related to this `metal vlan` command, facilities are returned per VLAN but not metros. 🐛

_Originally posted by @displague in https://github.com/equinix/metal-cli/issues/277#issuecomment-1585297439_

**Comment by displague** [comment]
This may be the case in other places where "[fF]acilities" is mentioned

**Comment by vielmetti** [comment]
bumping this back to visibility regarding facility deprecation @displague

**Comment by ctreatma** [comment]
This was fixed in #315, which initially went out in [v0.17.0](https://github.com/equinix/metal-cli/releases/tag/v0.17.0)
