### ISSUE TITLE
`metal hardware-reservations` does not include metros

### ISSUE THREAD

**Issue by displague** [StackPointCloud/packet-cli#286]
### What happened?

https://eqix-metal-community.slack.com/archives/C4FEV702E/p1686913291297669

> right now to check if we have a reserved node available at a certain metro we run `metal-cli hardware-reservations get -o json`  and then parse the output with `jq` to select provisionable nodes at a certain metro like so:  `select(.facility.metro.code==\"$METRO\" and .provisionable==true)` . The potential issue here is that we get the metro code from the facility schema, is there a better way to do this that doesn't involve going through the facility schema in json? I am running metal-cli version 0.14.1.

### What should happen?

The Metal CLI should expose the Metro field alongside the facility field.

**Comment by aayushrangwala** [comment]
@displague SInce this issue is fixed, can you please close it
