### ISSUE TITLE
Remove promptui library and calls

### ISSUE THREAD

**Issue by cprivitere** [StackPointCloud/packet-cli#331]
We use https://github.com/manifoldco/promptui in this project which seems to be [abandoned](https://github.com/manifoldco/promptui/issues/222). We should probably replace this code with something else.

**Comment by cprivitere** [comment]
https://github.com/search?q=repo%3Aequinix%2Fmetal-cli+%22github.com%2Fmanifoldco%2Fpromptui%22&type=code

**Comment by displague** [comment]
Closed via #407 

Along the way, #399 started an exploration into using more advanced UI toolkits including TUIs which could be part of an answer to #52.
