### ISSUE TITLE
Accept METAL_CONFIG env var in addition to --config

### ISSUE THREAD

**Issue by sagikazarmark** [StackPointCloud/packet-cli#360]
### What problem are you facing?

I'm opening this issue as a feature request rather than a bug, because from what I can tell this is the intended behavior at the moment.

It's still a confusing behavior though: currently `metal init` accepts the `METAL_CONFIG` env var as an override to the `--config` flag to write the generated configuration to a custom path.

After that though, any further invokations of the CLI requires manually passing the `--config` flag.

### How could the Equinix Metal CLI help solve this problem?

Accept the `METAL_CONFIG` env var in the rest of the commands when `--config` is not passed to the command.

**Comment by displague** [comment]
That makes complete sense.

I would offer a workaround, that everything you can define in the config file can be expressed as an environment variable, but I understand that there are distinct security sensitivities around passing environment variables around vs file names and handles.

**Comment by sagikazarmark** [comment]
I ended up doing that for the moment.

**Comment by displague** [comment]
> everything you can define in the config file can be expressed as an environment variable

That's not true. I set my default plan, OS, and metro via the config file. These are not exposed as environment variables.  The config file lets you define values for any`--something` arg.
