### ISSUE TITLE
Add support for creating a VRF IP Reservation

### ISSUE THREAD

**Issue by displague** [StackPointCloud/packet-cli#412]
### What problem are you facing?

Once I create a VRF, I can not create the IP reservations against that VRF.

https://deploy.equinix.com/developers/docs/metal/interconnections/vrf/#creating-a-vrf-ip-address-reservation
https://deploy.equinix.com/developers/api/metal/#tag/IPAddresses/operation/requestIPReservation (see the VRF tab)

Method | HTTP request | Description
------------- | ------------- | -------------
[**RequestIPReservation**](IPAddressesApi.md#RequestIPReservation) | **Post** /projects/{id}/ips | Requesting IP reservations
[**FindVrfIpReservation**](https://github.com/equinix-labs/metal-go/blob/main/docs/VRFsApi.md#FindVrfIpReservation) | **Get** /vrfs/{vrf_id}/ips/{id} | Retrieve all VRF IP Reservations in the VRF
[**FindVrfIpReservations**](https://github.com/equinix-labs/metal-go/blob/main/docs/VRFsApi.md#FindVrfIpReservations) | **Get** /vrfs/{id}/ips | Retrieve all VRF IP Reservations in the VRF

### How could the Equinix Metal CLI help solve this problem?

```
metal ips request --type vrf --vrf-id <id> --cidr <cidr, 22-29> --network <network, IP address> --tags foo --tags bar --customdata {"my":"goodness"} --details "i don't think VRF users need this or will see it after submitting the request"'

metal vrf --id <vrf_id> ips
metal vrf --id <vrf_id> ips --ip-id <ip_id>
```

Related to https://github.com/equinix/metal-cli/issues/268

**Comment by ctreatma** [comment]
Closed by #418
