### ISSUE TITLE
Add support for Metal VRF Routes

### ISSUE THREAD

**Issue by displague** [StackPointCloud/packet-cli#414]
### What problem are you facing?

With #268 there are a few features of VRF yet to be implemented. Among them is VRF Routes configuration.

https://github.com/equinix-labs/metal-go/blob/main/docs/VRFsApi.md

Method | HTTP request | Description
------------- | ------------- | -------------
[**CreateVrfRoute**](https://github.com/equinix-labs/metal-go/blob/main/docs/VRFsApi.md#CreateVrfRoute) | **Post** /vrfs/{id}/routes | Create a VRF route
[**DeleteVrfRouteById**](https://github.com/equinix-labs/metal-go/blob/main/docs/VRFsApi.md#DeleteVrfRouteById) | **Delete** /routes/{id} | Delete a VRF Route
[**FindVrfRouteById**](https://github.com/equinix-labs/metal-go/blob/main/docs/VRFsApi.md#FindVrfRouteById) | **Get** /routes/{id} | Retrieve a VRF Route
[**GetVrfRoutes**](https://github.com/equinix-labs/metal-go/blob/main/docs/VRFsApi.md#GetVrfRoutes) | **Get** /vrfs/{id}/routes | Retrieve all routes in the VRF
[**UpdateVrfRouteById**](https://github.com/equinix-labs/metal-go/blob/main/docs/VRFsApi.md#UpdateVrfRouteById) | **Put** /routes/{id} | Update a VRF Route

### How could the Equinix Metal CLI help solve this problem?

```
metal vrf routes-create --vrf-id {vrf_id}
metal vrf routes-update --route-id {route_id}
metal vrf routes-get --route-id {route_id}
metal vrf routes-delete --route-id {route_id}
```

One of these two ids should probably be "id" as an argument. Use whatever the current convention is for subcommands with IDs and when we use the short "id" vs the subcommand prefix.

**Comment by cprivitere** [comment]
When we create a vrf currently, we get the following output:

```
❯ metal vrf create  -m ch -r 192.168.1.1/29 -a 12003 -n testvrf
+---------+------+-------------+----------------+-------------------------------+---------+
|   ID    | NAME | DESCRIPTION |    LOCALASN    |           IPRANGES            | CREATED |
+---------+------+-------------+----------------+-------------------------------+---------+
| testvrf |      | 12003       | 192.168.1.0/29 | 2024-01-19 20:33:52 +0000 UTC |
+---------+------+-------------+----------------+-------------------------------+---------+
```

If you wait a sec and then run a get, you get something like this

```
+--------------------------------------+---------+-------------+----------------+----------+-------------------------------+
|                  ID                  |  NAME   | DESCRIPTION |    IPRANGES    | LOCALASN |            CREATED            |
+--------------------------------------+---------+-------------+----------------+----------+-------------------------------+
| 5ee64f98-fa3d-47f8-83c9-273dd7298147 | testvrf |             | 192.168.1.0/29 | 12003    | 2024-01-19 20:33:52 +0000 UTC |
+--------------------------------------+---------+-------------+----------------+----------+-------------------------------+
```
Ideally, the initial output should look more like the latter, at least putting fields in the right columns if we don't have all the info yet.
