### ISSUE TITLE
Add E2E Tests for interconnection subcommand in metal cli

### ISSUE THREAD

**Issue by aayushrangwala** [StackPointCloud/packet-cli#427]
### What problem are you facing?

We have added support for interconnections in metal-cli in https://github.com/equinix/metal-cli/pull/321
Need to add tests for the already existing support

### How could the Equinix Metal CLI help solve this problem?

Tests will run in CI and make sure reliability of the code

**Comment by ctreatma** [comment]
Not sure exactly which PR did it, but tests covering these subcommands were added
