### ISSUE TITLE
List ports by device ID

### ISSUE THREAD

**Issue by ctreatma** [StackPointCloud/packet-cli#478]
### What problem are you facing?

I have provisioned a device and I want to use metal-cli to view information about the device's ports.  The device's port IDs are not included in the output of `metal device get -i <device_id>`, and I have to know the port ID for all of the `metal port <subcommand>` subcommands.

This means that, if I only know the device ID, I have to run `metal device get -i <device_id> -o json` in order to get port information.  If I'm _not_ already planning on doing some post-processing on the JSON output, it's annoying to be forced to switch to JSON output and parse out the ports.

### How could the Equinix Metal CLI help solve this problem?

If `metal ports get` gained a `-d <device_id>` parameter (or similar) I could use the existing `metal ports get` command to find information about the ports belonging to a particular device.

**Comment by displague** [comment]
Related https://github.com/equinix/metal-cli/issues/215
